name: vedaweb_transformations
channels:
  - conda-forge
  - defaults
dependencies:
  - six==1.15.0
  - python-dateutil==2.8.1
  - titlecase==1.1.1
  - pytz==2020.4
  - pandas==1.1.5
  - numpy==1.19.4
  - regex==2020.11.13
  - xlrd==1.2.0
  - lxml==4.6.2
